#!/bin/sh
### BEGIN INIT INFO
# Provides:          nagios-api
# Required-Start:    $nagios
# Required-Stop:     $nagios
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop Nagios API
### END INIT INFO

set -e

. /lib/lsb/init-functions

DAEMON=/usr/local/bin/nagios-api
NAME="nagios-api"
DESC="Nagios API daemon"

[ -x "$DAEMON" ] || exit 0
[ -r /etc/default/nagios-api ] && . /etc/default/nagios-api

start () {
  if [ "$ENABLED" = "no"  ]; then
    log_warning_msg "Not starting Nagios API - set ENABLED to yes in /etc/default/nagios-api"
    exit 0
  fi

  echo -n "Starting $DESC: "
  start-stop-daemon --start --quiet --background --pidfile /var/run/$NAME.pid --exec $DAEMON -- $DAEMON_OPTS || true
  echo "$NAME."
}

stop () {
  echo -n "Stopping $DESC: "
  start-stop-daemon --stop --quiet --signal KILL --pidfile /var/run/$NAME.pid || true
  echo "$NAME."
  rm -f /var/run/$NAME.pid
}

restart () {
  echo -n "Restarting $DESC: "
  start-stop-daemon --stop --quiet --signal KILL --pidfile /var/run/$NAME.pid || true
  rm -f /var/run/$NAME.pid
  sleep 1
  start-stop-daemon --start --quiet --background --pidfile /var/run/$NAME.pid --exec $DAEMON -- $DAEMON_OPTS || true
  echo "$NAME."
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  status)
    status_of_proc -p /var/run/$NAME.pid "$DAEMON" nagios-api && exit 0 || exit $?
    ;;
  *)
    log_failure_msg "Usage: $0 {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0